import type {
  Customer,
  CustomerDiscount,
  CustomerInvoiceCustomField,
  CustomerTaxId,
  CustomerTaxRate,
} from './Customer';
import type { Invoice } from './Invoice';
import type {
  SubscriptionItem,
  SubscriptionItemList,
} from './SubscriptionItem';

/**
 * Stripe-compatible Subscription object for Zoneless.
 * Represents a customer's subscription to one or more recurring prices. Settled in USDC on Solana.
 *
 * @see https://docs.stripe.com/api/subscriptions/object
 */
export interface Subscription {
  /** Unique identifier for the object. */
  id: string;
  /** String representing the object's type. Objects of the same type share the same value. */
  object: 'subscription';
  /** ID of the Connect Application that created the subscription. Expandable. */
  application: string | null;
  /**
   * A non-negative decimal between 0 and 100, with at most two decimal places. This represents
   * the percentage of the subscription invoice total that will be transferred to the application
   * owner's account.
   */
  application_fee_percent: number | null;
  /** Automatic tax settings for this subscription. */
  automatic_tax: SubscriptionAutomaticTax;
  /**
   * The reference point that aligns future billing cycle dates. It sets the day of week for week
   * intervals, the day of month for month and year intervals, and the month of year for year
   * intervals. The timestamp is in UTC format.
   */
  billing_cycle_anchor: number;
  /** The fixed values used to calculate the billing_cycle_anchor. */
  billing_cycle_anchor_config: SubscriptionBillingCycleAnchorConfig | null;
  /** Controls how prorations and invoices for subscriptions are calculated and orchestrated. */
  billing_mode: SubscriptionBillingMode;
  /** Billing schedules for this subscription. */
  billing_schedules: SubscriptionBillingSchedule[];
  /**
   * Define thresholds at which an invoice will be sent, and the subscription advanced to a new
   * billing period.
   */
  billing_thresholds: SubscriptionBillingThresholds | null;
  /** A date in the future at which the subscription will automatically get canceled. */
  cancel_at: number | null;
  /**
   * Whether this subscription will (if status=active) or did (if status=canceled) cancel at the
   * end of the current billing period.
   */
  cancel_at_period_end: boolean;
  /**
   * If the subscription has been canceled, the date of that cancellation. If the subscription was
   * canceled with cancel_at_period_end, canceled_at will reflect the time of the most recent
   * update request, not the end of the subscription period when the subscription is automatically
   * moved to a canceled state.
   */
  canceled_at: number | null;
  /** Details about why this subscription was cancelled. */
  cancellation_details: SubscriptionCancellationDetails | null;
  /**
   * Either charge_automatically, or send_invoice. When charging automatically, Zoneless will
   * attempt to pay this subscription at the end of the cycle using the default source attached to
   * the customer. When sending an invoice, Zoneless will email your customer an invoice with
   * payment instructions and mark the subscription as active.
   */
  collection_method: 'charge_automatically' | 'send_invoice';
  /** Time at which the object was created. Measured in seconds since the Unix epoch. */
  created: number;
  /** Three-letter ISO currency code, in lowercase. Must be a supported currency. */
  currency: 'usdc';
  /** ID of the customer who owns the subscription. Expandable. */
  customer: string | Customer;
  /** ID of the account representing the customer who owns the subscription. */
  customer_account: string | null;
  /**
   * Number of days a customer has to pay invoices generated by this subscription. This value will
   * be null for subscriptions where collection_method=charge_automatically.
   */
  days_until_due: number | null;
  /**
   * ID of the default payment method for the subscription. It must belong to the customer
   * associated with the subscription. This takes precedence over default_source. If neither are
   * set, invoices will use the customer's invoice_settings.default_payment_method or
   * default_source. Expandable.
   */
  default_payment_method: string | null;
  /**
   * ID of the default payment source for the subscription. It must belong to the customer
   * associated with the subscription and be in a chargeable state. If default_payment_method is
   * also set, default_payment_method will take precedence. Expandable.
   */
  default_source: string | null;
  /**
   * The tax rates that will apply to any subscription item that does not have tax_rates set.
   * Invoices created will have their default_tax_rates populated from the subscription.
   */
  default_tax_rates: CustomerTaxRate[] | null;
  /**
   * The subscription's description, meant to be displayable to the customer. Use this field to
   * optionally store an explanation of the subscription for rendering in Zoneless surfaces.
   * The maximum length is 500 characters.
   */
  description: string | null;
  /**
   * The discounts applied to the subscription. Subscription item discounts are applied before
   * subscription discounts. Use `expand[]=discounts` to expand each discount.
   */
  discounts: (string | CustomerDiscount)[];
  /** If the subscription has ended, the date the subscription ended. */
  ended_at: number | null;
  /** All invoices will be billed using the specified settings. */
  invoice_settings: SubscriptionInvoiceSettings;
  /** List of subscription items, each with an attached price. */
  items: SubscriptionItemList;
  /**
   * The most recent invoice this subscription has generated over its lifecycle (for example, when
   * it cycles or is updated). Expandable.
   */
  latest_invoice: string | Invoice | null;
  /** If the object exists in live mode, the value is true. If the object exists in test mode, the value is false. */
  livemode: boolean;
  /** Settings for Managed Payments for this Subscription and resulting Invoices and PaymentIntents. */
  managed_payments: SubscriptionManagedPayments | null;
  /**
   * Set of key-value pairs that you can attach to an object. This can be useful for storing
   * additional information about the object in a structured format.
   */
  metadata: Record<string, string>;
  /**
   * Specifies the approximate timestamp on which any pending invoice items will be billed
   * according to the schedule provided at pending_invoice_item_interval.
   */
  next_pending_invoice_item_invoice: number | null;
  /**
   * The account (if any) the charge was made on behalf of for charges associated with this
   * subscription. Expandable.
   */
  on_behalf_of: string | null;
  /**
   * If specified, payment collection for this subscription will be paused. Note that the
   * subscription status will be unchanged and will not be updated to paused.
   */
  pause_collection: SubscriptionPauseCollection | null;
  /** Payment settings passed on to invoices created by the subscription. */
  payment_settings: SubscriptionPaymentSettings | null;
  /**
   * Specifies an interval for how often to bill for any pending invoice items. It is analogous
   * to calling Create an invoice for the given subscription at the specified interval.
   */
  pending_invoice_item_interval: SubscriptionPendingInvoiceItemInterval | null;
  /**
   * You can use this SetupIntent to collect user authentication when creating a subscription
   * without immediate payment or updating a subscription's payment method, allowing you to
   * optimize for off-session payments. Expandable.
   */
  pending_setup_intent: string | null;
  /**
   * If specified, pending updates that will be applied to the subscription once the
   * latest_invoice has been paid.
   */
  pending_update: SubscriptionPendingUpdate | null;
  /** A hash containing information about the currency presented to the customer. */
  presentment_details: SubscriptionPresentmentDetails | null;
  /** The schedule attached to the subscription. Expandable. */
  schedule: string | null;
  /**
   * Date when the subscription was first created. The date might differ from the created date
   * due to backdating.
   */
  start_date: number;
  /**
   * Possible values are incomplete, incomplete_expired, trialing, active, past_due, canceled,
   * unpaid, or paused.
   *
   * For collection_method=charge_automatically a subscription moves into incomplete if the
   * initial payment attempt fails. A subscription in this status can only have metadata and
   * default_source updated. Once the first invoice is paid, the subscription moves into an
   * active status. If the first invoice is not paid within 23 hours, the subscription
   * transitions to incomplete_expired. This is a terminal status, the open invoice will be
   * voided and no further invoices will be generated.
   *
   * A subscription that is currently in a trial period is trialing and moves to active when the
   * trial period is over.
   *
   * A subscription can only enter a paused status when a trial ends without a payment method. A
   * paused subscription doesn't generate invoices and can be resumed after your customer adds
   * their payment method. The paused status is different from pausing collection, which still
   * generates invoices and leaves the subscription's status unchanged.
   *
   * If subscription collection_method=charge_automatically, it becomes past_due when payment is
   * required but cannot be paid. Once Zoneless has exhausted all payment retry attempts, the
   * subscription will become canceled or unpaid (depending on your subscriptions settings).
   *
   * If subscription collection_method=send_invoice it becomes past_due when its invoice is not
   * paid by the due date, and canceled or unpaid if it is still not paid by an additional
   * deadline after that.
   */
  status: SubscriptionStatus;
  /** ID of the test clock this subscription belongs to. Expandable. */
  test_clock: string | null;
  /**
   * The account (if any) the subscription's payments will be attributed to for tax reporting, and
   * where funds from each payment will be transferred to for each of the subscription's invoices.
   */
  transfer_data: SubscriptionTransferData | null;
  /** If the subscription has a trial, the end of that trial. */
  trial_end: number | null;
  /** Settings related to subscription trials. */
  trial_settings: SubscriptionTrialSettings | null;
  /** If the subscription has a trial, the beginning of that trial. */
  trial_start: number | null;

  /**
   * The platform account that owns this resource.
   * @zoneless_extension
   */
  platform_account: string;
}

/** A list of subscriptions. */
export interface SubscriptionList {
  /** String representing the object's type. Objects of the same type share the same value. Always has the value list. */
  object: 'list';
  /** Details about each object. */
  data: Subscription[];
  /** True if this list has another page of items after this one that can be fetched. */
  has_more: boolean;
  /** The URL where this list can be accessed. */
  url: string;
}

/** Possible values for a subscription's status. */
export type SubscriptionStatus =
  | 'incomplete'
  | 'incomplete_expired'
  | 'trialing'
  | 'active'
  | 'past_due'
  | 'canceled'
  | 'unpaid'
  | 'paused';

// ─────────────────────────────────────────────────────────────────────────────
// Automatic tax
// ─────────────────────────────────────────────────────────────────────────────

/** Automatic tax settings for a subscription. */
export interface SubscriptionAutomaticTax {
  /** If Zoneless disabled automatic tax, this enum describes why. */
  disabled_reason: 'requires_location_inputs' | null;
  /** Whether Zoneless automatically computes tax on this subscription. */
  enabled: boolean;
  /**
   * The account that's liable for tax. If set, the business address and tax registrations
   * required to perform the tax calculation are loaded from this account. The tax transaction is
   * returned in the report of the connected account.
   */
  liability: SubscriptionTaxLiability | null;
}

/** The account that's liable for tax on a subscription. */
export interface SubscriptionTaxLiability {
  /** The connected account being referenced when type is account. Expandable. */
  account: string | null;
  /** Type of the account referenced. */
  type: 'account' | 'self';
}

// ─────────────────────────────────────────────────────────────────────────────
// Billing cycle anchor
// ─────────────────────────────────────────────────────────────────────────────

/** The fixed values used to calculate the billing_cycle_anchor. */
export interface SubscriptionBillingCycleAnchorConfig {
  /** The day of the month of the billing_cycle_anchor. */
  day_of_month: number;
  /** The hour of the day of the billing_cycle_anchor. */
  hour: number | null;
  /** The minute of the hour of the billing_cycle_anchor. */
  minute: number | null;
  /** The month to start full cycle billing periods. */
  month: number | null;
  /** The second of the minute of the billing_cycle_anchor. */
  second: number | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Billing mode
// ─────────────────────────────────────────────────────────────────────────────

/** Controls how prorations and invoices for subscriptions are calculated and orchestrated. */
export interface SubscriptionBillingMode {
  /** Configure behavior for flexible billing mode. */
  flexible: SubscriptionBillingModeFlexible | null;
  /** Controls how prorations and invoices for subscriptions are calculated and orchestrated. */
  type: 'classic' | 'flexible';
  /** Details on when the current billing_mode was adopted. */
  updated_at: number | null;
}

/** Configure behavior for flexible billing mode. */
export interface SubscriptionBillingModeFlexible {
  /** Controls how invoices and invoice items display proration amounts and discount amounts. */
  proration_discounts: 'included' | 'itemized';
}

// ─────────────────────────────────────────────────────────────────────────────
// Billing schedules
// ─────────────────────────────────────────────────────────────────────────────

/** A billing schedule for a subscription. */
export interface SubscriptionBillingSchedule {
  /** Specifies which subscription items the billing schedule applies to. */
  applies_to: SubscriptionBillingScheduleAppliesTo[] | null;
  /** Specifies the end of billing period. */
  bill_until: SubscriptionBillingScheduleBillUntil;
  /** Unique identifier for the billing schedule. */
  key: string;
}

/** Specifies which subscription items a billing schedule applies to. */
export interface SubscriptionBillingScheduleAppliesTo {
  /** The billing schedule will apply to the subscription item with the given price ID. Expandable. */
  price: string | null;
  /** Controls which subscription items the billing schedule applies to. */
  type: 'price';
}

/** Specifies the end of a billing schedule period. */
export interface SubscriptionBillingScheduleBillUntil {
  /** The timestamp the billing schedule will apply until. */
  computed_timestamp: number;
  /** Specifies the billing period. */
  duration: SubscriptionBillingScheduleDuration | null;
  /** If specified, the billing schedule will apply until the specified timestamp. */
  timestamp: number | null;
  /** Describes how the billing schedule will determine the end date. Either duration or timestamp. */
  type: 'duration' | 'timestamp';
}

/** Specifies a billing schedule duration. */
export interface SubscriptionBillingScheduleDuration {
  /** Specifies billing duration. Either day, week, month or year. */
  interval: 'day' | 'week' | 'month' | 'year';
  /** The multiplier applied to the interval. */
  interval_count: number | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Billing thresholds
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Define thresholds at which an invoice will be sent, and the subscription advanced to a new
 * billing period.
 */
export interface SubscriptionBillingThresholds {
  /** Monetary threshold that triggers the subscription to create an invoice. */
  amount_gte: number | null;
  /**
   * Indicates if the billing_cycle_anchor should be reset when a threshold is reached. If true,
   * billing_cycle_anchor will be updated to the date/time the threshold was last reached;
   * otherwise, the value will remain unchanged. This value may not be true if the subscription
   * contains items with plans that have aggregate_usage=last_ever.
   */
  reset_billing_cycle_anchor: boolean | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Cancellation
// ─────────────────────────────────────────────────────────────────────────────

/** Details about why a subscription was cancelled. */
export interface SubscriptionCancellationDetails {
  /**
   * Additional comments about why the user canceled the subscription, if the subscription was
   * canceled explicitly by the user.
   */
  comment: string | null;
  /**
   * The customer submitted reason for why they canceled, if the subscription was canceled
   * explicitly by the user.
   */
  feedback:
    | 'customer_service'
    | 'low_quality'
    | 'missing_features'
    | 'other'
    | 'switched_service'
    | 'too_complex'
    | 'too_expensive'
    | 'unused'
    | null;
  /** Why this subscription was canceled. */
  reason:
    | 'canceled_by_retention_policy'
    | 'cancellation_requested'
    | 'payment_disputed'
    | 'payment_failed'
    | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Invoice settings
// ─────────────────────────────────────────────────────────────────────────────

/** All invoices for a subscription will be billed using the specified settings. */
export interface SubscriptionInvoiceSettings {
  /**
   * The account tax IDs associated with the subscription. Will be set on invoices generated by
   * the subscription. Expandable.
   */
  account_tax_ids: (string | CustomerTaxId)[] | null;
  /** A list of up to 4 custom fields to be displayed on the invoice. */
  custom_fields: CustomerInvoiceCustomField[] | null;
  /** An arbitrary string attached to the object. Often useful for displaying to users. */
  description: string | null;
  /** Footer to be displayed on the invoice. */
  footer: string | null;
  /**
   * The connected account that issues the invoice. The invoice is presented with the branding
   * and support information of the specified account.
   */
  issuer: SubscriptionIssuer;
}

/** The connected account that issues invoices for a subscription. */
export interface SubscriptionIssuer {
  /** The connected account being referenced when type is account. Expandable. */
  account: string | null;
  /** Type of the account referenced. */
  type: 'account' | 'self';
}

// ─────────────────────────────────────────────────────────────────────────────
// Managed payments
// ─────────────────────────────────────────────────────────────────────────────

/** Settings for Managed Payments for a Subscription and resulting Invoices and PaymentIntents. */
export interface SubscriptionManagedPayments {
  /**
   * Indicates whether Managed Payments is enabled for this Subscription and resulting Invoices
   * and PaymentIntents.
   */
  enabled: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Pause collection
// ─────────────────────────────────────────────────────────────────────────────

/** If specified, payment collection for this subscription will be paused. */
export interface SubscriptionPauseCollection {
  /** The payment collection behavior for this subscription while paused. */
  behavior: 'keep_as_draft' | 'mark_uncollectible' | 'void';
  /** The time after which the subscription will resume collecting payments. */
  resumes_at: number | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Payment settings
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Payment settings passed on to invoices created by the subscription.
 * @remarks Simplified from Stripe's payment_settings, which also exposes
 * payment_method_options for many fiat rails (ACH, cards, iDEAL, etc.) that Zoneless doesn't
 * support since all payments are settled in USDC. Matches the simplification on Invoice.
 */
export interface SubscriptionPaymentSettings {
  /**
   * Payment-method-specific configuration to provide to invoices created by the subscription.
   * Opaque stub for Stripe API parity; Zoneless settles invoices in USDC.
   */
  payment_method_options: object | null;
  /**
   * The list of payment method types to provide to every invoice created by the subscription. If
   * not set, Zoneless attempts to automatically determine the types to use.
   */
  payment_method_types: string[] | null;
  /**
   * Configure whether Zoneless updates subscription.default_payment_method when payment succeeds.
   * Defaults to off.
   */
  save_default_payment_method: 'off' | 'on_subscription' | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Pending invoice item interval
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Specifies an interval for how often to bill for any pending invoice items. It is analogous to
 * calling Create an invoice for the given subscription at the specified interval.
 */
export interface SubscriptionPendingInvoiceItemInterval {
  /** Specifies invoicing frequency. Either day, week, month or year. */
  interval: 'day' | 'week' | 'month' | 'year';
  /**
   * The number of intervals between invoices. For example, interval=month and interval_count=3
   * bills every 3 months. Maximum of one year interval allowed (1 year, 12 months, or 52 weeks).
   */
  interval_count: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Pending update
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Pending updates that will be applied to the subscription once the latest_invoice has been paid.
 */
export interface SubscriptionPendingUpdate {
  /**
   * If the update is applied, determines the date of the first full invoice, and, for plans with
   * month or year intervals, the day of the month for subsequent invoices. The timestamp is in
   * UTC format.
   */
  billing_cycle_anchor: number | null;
  /** The pending subscription-level discount that will be applied when the pending update is applied. */
  discount: CustomerDiscount | null;
  /**
   * The discounts that will be applied to the subscription when the pending update is applied.
   * Use `expand[]=discounts` to expand each discount.
   */
  discounts: (string | CustomerDiscount)[] | null;
  /** The point after which the changes reflected by this update will be discarded and no longer applied. */
  expires_at: number;
  /**
   * Set of key-value pairs that you can attach to an object. This can be useful for storing
   * additional information about the object in a structured format.
   */
  metadata: Record<string, string> | null;
  /** List of subscription items, each with an attached plan, that will be set if the update is applied. */
  subscription_items: SubscriptionItem[] | null;
  /**
   * Unix timestamp representing the end of the trial period the customer will get before being
   * charged for the first time, if the update is applied.
   */
  trial_end: number | null;
  /**
   * Indicates if a plan's trial_period_days should be applied to the subscription. Setting
   * trial_end per subscription is preferred, and this defaults to false. Setting this flag to
   * true together with trial_end is not allowed.
   */
  trial_from_plan: boolean | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Presentment details
// ─────────────────────────────────────────────────────────────────────────────

/** A hash containing information about the currency presented to the customer. */
export interface SubscriptionPresentmentDetails {
  /** Currency used for customer payments. */
  presentment_currency: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Transfer data
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The account (if any) the subscription's payments will be attributed to for tax reporting, and
 * where funds from each payment will be transferred to for each of the subscription's invoices.
 */
export interface SubscriptionTransferData {
  /**
   * A non-negative decimal between 0 and 100, with at most two decimal places. This represents
   * the percentage of the subscription invoice total that will be transferred to the destination
   * account. By default, the entire amount is transferred to the destination.
   */
  amount_percent: number | null;
  /** The account where funds from the payment will be transferred to upon payment success. Expandable. */
  destination: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Trial settings
// ─────────────────────────────────────────────────────────────────────────────

/** Settings related to subscription trials. */
export interface SubscriptionTrialSettings {
  /** Defines how the subscription should behave when the user's trial ends. */
  end_behavior: SubscriptionTrialEndBehavior;
}

/** Defines how the subscription should behave when the user's trial ends. */
export interface SubscriptionTrialEndBehavior {
  /**
   * Indicates how the subscription should change when the trial ends if the user did not provide
   * a payment method.
   */
  missing_payment_method: 'cancel' | 'create_invoice' | 'pause';
}
