export interface CountryCode {
  country: string;
  code: string;
  currency: string;
  timezone: string;
  emoji: string;
  dialCode: string;
  phoneExample: string;
}

export const ISO_CODES: CountryCode[] = [
  {
    country: 'Afghanistan',
    code: 'AF',
    currency: 'afn',
    timezone: 'Asia/Kabul',
    emoji: '🇦🇫',
    dialCode: '+93',
    phoneExample: '70 123 4567',
  },
  {
    country: 'Albania',
    code: 'AL',
    currency: 'all',
    timezone: 'Europe/Tirane',
    emoji: '🇦🇱',
    dialCode: '+355',
    phoneExample: '66 123 4567',
  },
  {
    country: 'Algeria',
    code: 'DZ',
    currency: 'dzd',
    timezone: 'Africa/Algiers',
    emoji: '🇩🇿',
    dialCode: '+213',
    phoneExample: '551 23 45 67',
  },
  {
    country: 'American Samoa',
    code: 'AS',
    currency: 'usd',
    timezone: 'Pacific/Pago_Pago',
    emoji: '🇦🇸',
    dialCode: '+1684',
    phoneExample: '733 1234',
  },
  {
    country: 'Andorra',
    code: 'AD',
    currency: 'eur',
    timezone: 'Europe/Andorra',
    emoji: '🇦🇩',
    dialCode: '+376',
    phoneExample: '312 345',
  },
  {
    country: 'Angola',
    code: 'AO',
    currency: 'aoa',
    timezone: 'Africa/Luanda',
    emoji: '🇦🇴',
    dialCode: '+244',
    phoneExample: '923 123 456',
  },
  {
    country: 'Anguilla',
    code: 'AI',
    currency: 'xcd',
    timezone: 'America/Anguilla',
    emoji: '🇦🇮',
    dialCode: '+1264',
    phoneExample: '235 1234',
  },
  {
    country: 'Antigua & Barbuda',
    code: 'AG',
    currency: 'xcd',
    timezone: 'America/Antigua',
    emoji: '🇦🇬',
    dialCode: '+1268',
    phoneExample: '464 1234',
  },
  {
    country: 'Argentina',
    code: 'AR',
    currency: 'ars',
    timezone: 'America/Argentina/Buenos_Aires',
    emoji: '🇦🇷',
    dialCode: '+54',
    phoneExample: '9 11 1234 5678',
  },
  {
    country: 'Armenia',
    code: 'AM',
    currency: 'amd',
    timezone: 'Asia/Yerevan',
    emoji: '🇦🇲',
    dialCode: '+374',
    phoneExample: '77 123456',
  },
  {
    country: 'Aruba',
    code: 'AW',
    currency: 'awg',
    timezone: 'America/Aruba',
    emoji: '🇦🇼',
    dialCode: '+297',
    phoneExample: '560 1234',
  },
  {
    country: 'Australia',
    code: 'AU',
    currency: 'aud',
    timezone: 'Australia/Sydney',
    emoji: '🇦🇺',
    dialCode: '+61',
    phoneExample: '412 345 678',
  },
  {
    country: 'Austria',
    code: 'AT',
    currency: 'eur',
    timezone: 'Europe/Vienna',
    emoji: '🇦🇹',
    dialCode: '+43',
    phoneExample: '664 1234567',
  },
  {
    country: 'Azerbaijan',
    code: 'AZ',
    currency: 'azn',
    timezone: 'Asia/Baku',
    emoji: '🇦🇿',
    dialCode: '+994',
    phoneExample: '40 123 45 67',
  },
  {
    country: 'Bahamas',
    code: 'BS',
    currency: 'bsd',
    timezone: 'America/Nassau',
    emoji: '🇧🇸',
    dialCode: '+1242',
    phoneExample: '359 1234',
  },
  {
    country: 'Bahrain',
    code: 'BH',
    currency: 'bhd',
    timezone: 'Asia/Bahrain',
    emoji: '🇧🇭',
    dialCode: '+973',
    phoneExample: '3600 1234',
  },
  {
    country: 'Bangladesh',
    code: 'BD',
    currency: 'bdt',
    timezone: 'Asia/Dhaka',
    emoji: '🇧🇩',
    dialCode: '+880',
    phoneExample: '1812 345678',
  },
  {
    country: 'Barbados',
    code: 'BB',
    currency: 'bbd',
    timezone: 'America/Barbados',
    emoji: '🇧🇧',
    dialCode: '+1246',
    phoneExample: '250 1234',
  },
  {
    country: 'Belarus',
    code: 'BY',
    currency: 'byn',
    timezone: 'Europe/Minsk',
    emoji: '🇧🇾',
    dialCode: '+375',
    phoneExample: '29 491 19 11',
  },
  {
    country: 'Belgium',
    code: 'BE',
    currency: 'eur',
    timezone: 'Europe/Brussels',
    emoji: '🇧🇪',
    dialCode: '+32',
    phoneExample: '470 12 34 56',
  },
  {
    country: 'Belize',
    code: 'BZ',
    currency: 'bzd',
    timezone: 'America/Belize',
    emoji: '🇧🇿',
    dialCode: '+501',
    phoneExample: '622 1234',
  },
  {
    country: 'Benin',
    code: 'BJ',
    currency: 'xof',
    timezone: 'Africa/Porto-Novo',
    emoji: '🇧🇯',
    dialCode: '+229',
    phoneExample: '90 01 12 34',
  },
  {
    country: 'Bermuda',
    code: 'BM',
    currency: 'bmd',
    timezone: 'Atlantic/Bermuda',
    emoji: '🇧🇲',
    dialCode: '+1441',
    phoneExample: '370 1234',
  },
  {
    country: 'Bhutan',
    code: 'BT',
    currency: 'btn',
    timezone: 'Asia/Thimphu',
    emoji: '🇧🇹',
    dialCode: '+975',
    phoneExample: '17 12 34 56',
  },
  {
    country: 'Bolivia',
    code: 'BO',
    currency: 'bob',
    timezone: 'America/La_Paz',
    emoji: '🇧🇴',
    dialCode: '+591',
    phoneExample: '71234567',
  },
  {
    country: 'Bosnia & Herzegovina',
    code: 'BA',
    currency: 'bam',
    timezone: 'Europe/Sarajevo',
    emoji: '🇧🇦',
    dialCode: '+387',
    phoneExample: '61 123 456',
  },
  {
    country: 'Botswana',
    code: 'BW',
    currency: 'bwp',
    timezone: 'Africa/Gaborone',
    emoji: '🇧🇼',
    dialCode: '+267',
    phoneExample: '71 123 456',
  },
  {
    country: 'Brazil',
    code: 'BR',
    currency: 'brl',
    timezone: 'America/Sao_Paulo',
    emoji: '🇧🇷',
    dialCode: '+55',
    phoneExample: '11 91234 5678',
  },
  {
    country: 'British Virgin Islands',
    code: 'VG',
    currency: 'usd',
    timezone: 'America/Tortola',
    emoji: '🇻🇬',
    dialCode: '+1284',
    phoneExample: '300 1234',
  },
  {
    country: 'Brunei',
    code: 'BN',
    currency: 'bnd',
    timezone: 'Asia/Brunei',
    emoji: '🇧🇳',
    dialCode: '+673',
    phoneExample: '712 3456',
  },
  {
    country: 'Bulgaria',
    code: 'BG',
    currency: 'bgn',
    timezone: 'Europe/Sofia',
    emoji: '🇧🇬',
    dialCode: '+359',
    phoneExample: '48 123 456',
  },
  {
    country: 'Burkina Faso',
    code: 'BF',
    currency: 'xof',
    timezone: 'Africa/Ouagadougou',
    emoji: '🇧🇫',
    dialCode: '+226',
    phoneExample: '70 12 34 56',
  },
  {
    country: 'Burundi',
    code: 'BI',
    currency: 'bif',
    timezone: 'Africa/Bujumbura',
    emoji: '🇧🇮',
    dialCode: '+257',
    phoneExample: '79 56 12 34',
  },
  {
    country: 'Cabo Verde',
    code: 'CV',
    currency: 'cve',
    timezone: 'Atlantic/Cape_Verde',
    emoji: '🇨🇻',
    dialCode: '+238',
    phoneExample: '991 12 34',
  },
  {
    country: 'Cambodia',
    code: 'KH',
    currency: 'khr',
    timezone: 'Asia/Phnom_Penh',
    emoji: '🇰🇭',
    dialCode: '+855',
    phoneExample: '91 234 567',
  },
  {
    country: 'Cameroon',
    code: 'CM',
    currency: 'xaf',
    timezone: 'Africa/Douala',
    emoji: '🇨🇲',
    dialCode: '+237',
    phoneExample: '2 34 56 78 90',
  },
  {
    country: 'Canada',
    code: 'CA',
    currency: 'cad',
    timezone: 'America/Toronto',
    emoji: '🇨🇦',
    dialCode: '+1',
    phoneExample: '555 123 4567',
  },
  {
    country: 'Cayman Islands',
    code: 'KY',
    currency: 'kyd',
    timezone: 'America/Cayman',
    emoji: '🇰🇾',
    dialCode: '+1345',
    phoneExample: '323 1234',
  },
  {
    country: 'Central African Republic',
    code: 'CF',
    currency: 'xaf',
    timezone: 'Africa/Bangui',
    emoji: '🇨🇫',
    dialCode: '+236',
    phoneExample: '70 01 23 45',
  },
  {
    country: 'Chad',
    code: 'TD',
    currency: 'xaf',
    timezone: 'Africa/Ndjamena',
    emoji: '🇹🇩',
    dialCode: '+235',
    phoneExample: '63 01 23 45',
  },
  {
    country: 'Chile',
    code: 'CL',
    currency: 'clp',
    timezone: 'America/Santiago',
    emoji: '🇨🇱',
    dialCode: '+56',
    phoneExample: '9 6123 4567',
  },
  {
    country: 'China',
    code: 'CN',
    currency: 'cny',
    timezone: 'Asia/Shanghai',
    emoji: '🇨🇳',
    dialCode: '+86',
    phoneExample: '131 2345 6789',
  },
  {
    country: 'Colombia',
    code: 'CO',
    currency: 'cop',
    timezone: 'America/Bogota',
    emoji: '🇨🇴',
    dialCode: '+57',
    phoneExample: '321 1234567',
  },
  {
    country: 'Comoros',
    code: 'KM',
    currency: 'kmf',
    timezone: 'Indian/Comoro',
    emoji: '🇰🇲',
    dialCode: '+269',
    phoneExample: '321 23 45',
  },
  {
    country: 'Congo - Brazzaville',
    code: 'CG',
    currency: 'xaf',
    timezone: 'Africa/Brazzaville',
    emoji: '🇨🇬',
    dialCode: '+242',
    phoneExample: '06 123 4567',
  },
  {
    country: 'Congo - Kinshasa',
    code: 'CD',
    currency: 'cdf',
    timezone: 'Africa/Kinshasa',
    emoji: '🇨🇩',
    dialCode: '+243',
    phoneExample: '991 234 567',
  },
  {
    country: 'Cook Islands',
    code: 'CK',
    currency: 'nzd',
    timezone: 'Pacific/Rarotonga',
    emoji: '🇨🇰',
    dialCode: '+682',
    phoneExample: '71 234',
  },
  {
    country: 'Costa Rica',
    code: 'CR',
    currency: 'crc',
    timezone: 'America/Costa_Rica',
    emoji: '🇨🇷',
    dialCode: '+506',
    phoneExample: '8312 3456',
  },
  {
    country: "Côte d'Ivoire",
    code: 'CI',
    currency: 'xof',
    timezone: 'Africa/Abidjan',
    emoji: '🇨🇮',
    dialCode: '+225',
    phoneExample: '01 23 45 67',
  },
  {
    country: 'Croatia',
    code: 'HR',
    currency: 'hrk',
    timezone: 'Europe/Zagreb',
    emoji: '🇭🇷',
    dialCode: '+385',
    phoneExample: '91 234 5678',
  },
  {
    country: 'Curaçao',
    code: 'CW',
    currency: 'ang',
    timezone: 'America/Curacao',
    emoji: '🇨🇼',
    dialCode: '+599',
    phoneExample: '9 518 1234',
  },
  {
    country: 'Cyprus',
    code: 'CY',
    currency: 'eur',
    timezone: 'Asia/Nicosia',
    emoji: '🇨🇾',
    dialCode: '+357',
    phoneExample: '96 123456',
  },
  {
    country: 'Czech Republic',
    code: 'CZ',
    currency: 'czk',
    timezone: 'Europe/Prague',
    emoji: '🇨🇿',
    dialCode: '+420',
    phoneExample: '601 123 456',
  },
  {
    country: 'Denmark',
    code: 'DK',
    currency: 'dkk',
    timezone: 'Europe/Copenhagen',
    emoji: '🇩🇰',
    dialCode: '+45',
    phoneExample: '20 12 34 56',
  },
  {
    country: 'Djibouti',
    code: 'DJ',
    currency: 'djf',
    timezone: 'Africa/Djibouti',
    emoji: '🇩🇯',
    dialCode: '+253',
    phoneExample: '77 83 10 01',
  },
  {
    country: 'Dominica',
    code: 'DM',
    currency: 'xcd',
    timezone: 'America/Dominica',
    emoji: '🇩🇲',
    dialCode: '+1767',
    phoneExample: '225 1234',
  },
  {
    country: 'Dominican Republic',
    code: 'DO',
    currency: 'dop',
    timezone: 'America/Santo_Domingo',
    emoji: '🇩🇴',
    dialCode: '+1809',
    phoneExample: '234 5678',
  },
  {
    country: 'Ecuador',
    code: 'EC',
    currency: 'usd',
    timezone: 'America/Guayaquil',
    emoji: '🇪🇨',
    dialCode: '+593',
    phoneExample: '99 123 4567',
  },
  {
    country: 'Egypt',
    code: 'EG',
    currency: 'egp',
    timezone: 'Africa/Cairo',
    emoji: '🇪🇬',
    dialCode: '+20',
    phoneExample: '100 123 4567',
  },
  {
    country: 'El Salvador',
    code: 'SV',
    currency: 'usd',
    timezone: 'America/El_Salvador',
    emoji: '🇸🇻',
    dialCode: '+503',
    phoneExample: '7012 3456',
  },
  {
    country: 'Equatorial Guinea',
    code: 'GQ',
    currency: 'xaf',
    timezone: 'Africa/Malabo',
    emoji: '🇬🇶',
    dialCode: '+240',
    phoneExample: '222 123 456',
  },
  {
    country: 'Eritrea',
    code: 'ER',
    currency: 'ern',
    timezone: 'Africa/Asmara',
    emoji: '🇪🇷',
    dialCode: '+291',
    phoneExample: '7 123 456',
  },
  {
    country: 'Estonia',
    code: 'EE',
    currency: 'eur',
    timezone: 'Europe/Tallinn',
    emoji: '🇪🇪',
    dialCode: '+372',
    phoneExample: '5123 4567',
  },
  {
    country: 'Eswatini',
    code: 'SZ',
    currency: 'szl',
    timezone: 'Africa/Mbabane',
    emoji: '🇸🇿',
    dialCode: '+268',
    phoneExample: '7612 3456',
  },
  {
    country: 'Ethiopia',
    code: 'ET',
    currency: 'etb',
    timezone: 'Africa/Addis_Ababa',
    emoji: '🇪🇹',
    dialCode: '+251',
    phoneExample: '91 123 4567',
  },
  {
    country: 'Faroe Islands',
    code: 'FO',
    currency: 'dkk',
    timezone: 'Atlantic/Faroe',
    emoji: '🇫🇴',
    dialCode: '+298',
    phoneExample: '211234',
  },
  {
    country: 'Fiji',
    code: 'FJ',
    currency: 'fjd',
    timezone: 'Pacific/Fiji',
    emoji: '🇫🇯',
    dialCode: '+679',
    phoneExample: '701 2345',
  },
  {
    country: 'Finland',
    code: 'FI',
    currency: 'eur',
    timezone: 'Europe/Helsinki',
    emoji: '🇫🇮',
    dialCode: '+358',
    phoneExample: '41 2345678',
  },
  {
    country: 'France',
    code: 'FR',
    currency: 'eur',
    timezone: 'Europe/Paris',
    emoji: '🇫🇷',
    dialCode: '+33',
    phoneExample: '6 12 34 56 78',
  },
  {
    country: 'French Guiana',
    code: 'GF',
    currency: 'eur',
    timezone: 'America/Cayenne',
    emoji: '🇬🇫',
    dialCode: '+594',
    phoneExample: '694 20 12 34',
  },
  {
    country: 'French Polynesia',
    code: 'PF',
    currency: 'xpf',
    timezone: 'Pacific/Tahiti',
    emoji: '🇵🇫',
    dialCode: '+689',
    phoneExample: '87 12 34 56',
  },
  {
    country: 'Gabon',
    code: 'GA',
    currency: 'xaf',
    timezone: 'Africa/Libreville',
    emoji: '🇬🇦',
    dialCode: '+241',
    phoneExample: '06 03 12 34',
  },
  {
    country: 'Gambia',
    code: 'GM',
    currency: 'gmd',
    timezone: 'Africa/Banjul',
    emoji: '🇬🇲',
    dialCode: '+220',
    phoneExample: '301 2345',
  },
  {
    country: 'Georgia',
    code: 'GE',
    currency: 'gel',
    timezone: 'Asia/Tbilisi',
    emoji: '🇬🇪',
    dialCode: '+995',
    phoneExample: '555 12 34 56',
  },
  {
    country: 'Germany',
    code: 'DE',
    currency: 'eur',
    timezone: 'Europe/Berlin',
    emoji: '🇩🇪',
    dialCode: '+49',
    phoneExample: '151 12345678',
  },
  {
    country: 'Ghana',
    code: 'GH',
    currency: 'ghs',
    timezone: 'Africa/Accra',
    emoji: '🇬🇭',
    dialCode: '+233',
    phoneExample: '23 123 4567',
  },
  {
    country: 'Gibraltar',
    code: 'GI',
    currency: 'gbp',
    timezone: 'Europe/Gibraltar',
    emoji: '🇬🇮',
    dialCode: '+350',
    phoneExample: '5712 3456',
  },
  {
    country: 'Greece',
    code: 'GR',
    currency: 'eur',
    timezone: 'Europe/Athens',
    emoji: '🇬🇷',
    dialCode: '+30',
    phoneExample: '691 234 5678',
  },
  {
    country: 'Greenland',
    code: 'GL',
    currency: 'dkk',
    timezone: 'America/Nuuk',
    emoji: '🇬🇱',
    dialCode: '+299',
    phoneExample: '22 12 34',
  },
  {
    country: 'Grenada',
    code: 'GD',
    currency: 'xcd',
    timezone: 'America/Grenada',
    emoji: '🇬🇩',
    dialCode: '+1473',
    phoneExample: '403 1234',
  },
  {
    country: 'Guadeloupe',
    code: 'GP',
    currency: 'eur',
    timezone: 'America/Guadeloupe',
    emoji: '🇬🇵',
    dialCode: '+590',
    phoneExample: '690 00 12 34',
  },
  {
    country: 'Guam',
    code: 'GU',
    currency: 'usd',
    timezone: 'Pacific/Guam',
    emoji: '🇬🇺',
    dialCode: '+1671',
    phoneExample: '300 1234',
  },
  {
    country: 'Guatemala',
    code: 'GT',
    currency: 'gtq',
    timezone: 'America/Guatemala',
    emoji: '🇬🇹',
    dialCode: '+502',
    phoneExample: '5123 4567',
  },
  {
    country: 'Guernsey',
    code: 'GG',
    currency: 'gbp',
    timezone: 'Europe/Guernsey',
    emoji: '🇬🇬',
    dialCode: '+44',
    phoneExample: '7781 123456',
  },
  {
    country: 'Guinea',
    code: 'GN',
    currency: 'gnf',
    timezone: 'Africa/Conakry',
    emoji: '🇬🇳',
    dialCode: '+224',
    phoneExample: '601 12 34 56',
  },
  {
    country: 'Guinea-Bissau',
    code: 'GW',
    currency: 'xof',
    timezone: 'Africa/Bissau',
    emoji: '🇬🇼',
    dialCode: '+245',
    phoneExample: '955 012 345',
  },
  {
    country: 'Guyana',
    code: 'GY',
    currency: 'gyd',
    timezone: 'America/Guyana',
    emoji: '🇬🇾',
    dialCode: '+592',
    phoneExample: '609 1234',
  },
  {
    country: 'Haiti',
    code: 'HT',
    currency: 'htg',
    timezone: 'America/Port-au-Prince',
    emoji: '🇭🇹',
    dialCode: '+509',
    phoneExample: '34 10 1234',
  },
  {
    country: 'Honduras',
    code: 'HN',
    currency: 'hnl',
    timezone: 'America/Tegucigalpa',
    emoji: '🇭🇳',
    dialCode: '+504',
    phoneExample: '9123 4567',
  },
  {
    country: 'Hong Kong',
    code: 'HK',
    currency: 'hkd',
    timezone: 'Asia/Hong_Kong',
    emoji: '🇭🇰',
    dialCode: '+852',
    phoneExample: '5123 4567',
  },
  {
    country: 'Hungary',
    code: 'HU',
    currency: 'huf',
    timezone: 'Europe/Budapest',
    emoji: '🇭🇺',
    dialCode: '+36',
    phoneExample: '20 123 4567',
  },
  {
    country: 'Iceland',
    code: 'IS',
    currency: 'isk',
    timezone: 'Atlantic/Reykjavik',
    emoji: '🇮🇸',
    dialCode: '+354',
    phoneExample: '611 1234',
  },
  {
    country: 'India',
    code: 'IN',
    currency: 'inr',
    timezone: 'Asia/Kolkata',
    emoji: '🇮🇳',
    dialCode: '+91',
    phoneExample: '81234 56789',
  },
  {
    country: 'Indonesia',
    code: 'ID',
    currency: 'idr',
    timezone: 'Asia/Jakarta',
    emoji: '🇮🇩',
    dialCode: '+62',
    phoneExample: '812 345 6789',
  },
  {
    country: 'Iraq',
    code: 'IQ',
    currency: 'iqd',
    timezone: 'Asia/Baghdad',
    emoji: '🇮🇶',
    dialCode: '+964',
    phoneExample: '791 234 5678',
  },
  {
    country: 'Ireland',
    code: 'IE',
    currency: 'eur',
    timezone: 'Europe/Dublin',
    emoji: '🇮🇪',
    dialCode: '+353',
    phoneExample: '85 012 3456',
  },
  {
    country: 'Isle of Man',
    code: 'IM',
    currency: 'gbp',
    timezone: 'Europe/Isle_of_Man',
    emoji: '🇮🇲',
    dialCode: '+44',
    phoneExample: '7924 123456',
  },
  {
    country: 'Israel',
    code: 'IL',
    currency: 'ils',
    timezone: 'Asia/Jerusalem',
    emoji: '🇮🇱',
    dialCode: '+972',
    phoneExample: '50 123 4567',
  },
  {
    country: 'Italy',
    code: 'IT',
    currency: 'eur',
    timezone: 'Europe/Rome',
    emoji: '🇮🇹',
    dialCode: '+39',
    phoneExample: '312 345 6789',
  },
  {
    country: 'Jamaica',
    code: 'JM',
    currency: 'jmd',
    timezone: 'America/Jamaica',
    emoji: '🇯🇲',
    dialCode: '+1876',
    phoneExample: '210 1234',
  },
  {
    country: 'Japan',
    code: 'JP',
    currency: 'jpy',
    timezone: 'Asia/Tokyo',
    emoji: '🇯🇵',
    dialCode: '+81',
    phoneExample: '90 1234 5678',
  },
  {
    country: 'Jersey',
    code: 'JE',
    currency: 'gbp',
    timezone: 'Europe/Jersey',
    emoji: '🇯🇪',
    dialCode: '+44',
    phoneExample: '7797 123456',
  },
  {
    country: 'Jordan',
    code: 'JO',
    currency: 'jod',
    timezone: 'Asia/Amman',
    emoji: '🇯🇴',
    dialCode: '+962',
    phoneExample: '7 9012 3456',
  },
  {
    country: 'Kazakhstan',
    code: 'KZ',
    currency: 'kzt',
    timezone: 'Asia/Almaty',
    emoji: '🇰🇿',
    dialCode: '+7',
    phoneExample: '771 000 9998',
  },
  {
    country: 'Kenya',
    code: 'KE',
    currency: 'kes',
    timezone: 'Africa/Nairobi',
    emoji: '🇰🇪',
    dialCode: '+254',
    phoneExample: '712 123456',
  },
  {
    country: 'Kiribati',
    code: 'KI',
    currency: 'aud',
    timezone: 'Pacific/Tarawa',
    emoji: '🇰🇮',
    dialCode: '+686',
    phoneExample: '7201 2345',
  },
  {
    country: 'Kosovo',
    code: 'XK',
    currency: 'eur',
    timezone: 'Europe/Belgrade',
    emoji: '🇽🇰',
    dialCode: '+383',
    phoneExample: '43 201 234',
  },
  {
    country: 'Kuwait',
    code: 'KW',
    currency: 'kwd',
    timezone: 'Asia/Kuwait',
    emoji: '🇰🇼',
    dialCode: '+965',
    phoneExample: '500 12345',
  },
  {
    country: 'Kyrgyzstan',
    code: 'KG',
    currency: 'kgs',
    timezone: 'Asia/Bishkek',
    emoji: '🇰🇬',
    dialCode: '+996',
    phoneExample: '700 123 456',
  },
  {
    country: 'Laos',
    code: 'LA',
    currency: 'lak',
    timezone: 'Asia/Vientiane',
    emoji: '🇱🇦',
    dialCode: '+856',
    phoneExample: '20 23 123 456',
  },
  {
    country: 'Latvia',
    code: 'LV',
    currency: 'eur',
    timezone: 'Europe/Riga',
    emoji: '🇱🇻',
    dialCode: '+371',
    phoneExample: '21 234 567',
  },
  {
    country: 'Lebanon',
    code: 'LB',
    currency: 'lbp',
    timezone: 'Asia/Beirut',
    emoji: '🇱🇧',
    dialCode: '+961',
    phoneExample: '71 123 456',
  },
  {
    country: 'Lesotho',
    code: 'LS',
    currency: 'lsl',
    timezone: 'Africa/Maseru',
    emoji: '🇱🇸',
    dialCode: '+266',
    phoneExample: '5012 3456',
  },
  {
    country: 'Liberia',
    code: 'LR',
    currency: 'lrd',
    timezone: 'Africa/Monrovia',
    emoji: '🇱🇷',
    dialCode: '+231',
    phoneExample: '77 012 3456',
  },
  {
    country: 'Libya',
    code: 'LY',
    currency: 'lyd',
    timezone: 'Africa/Tripoli',
    emoji: '🇱🇾',
    dialCode: '+218',
    phoneExample: '91 2345678',
  },
  {
    country: 'Liechtenstein',
    code: 'LI',
    currency: 'chf',
    timezone: 'Europe/Vaduz',
    emoji: '🇱🇮',
    dialCode: '+423',
    phoneExample: '660 1234',
  },
  {
    country: 'Lithuania',
    code: 'LT',
    currency: 'eur',
    timezone: 'Europe/Vilnius',
    emoji: '🇱🇹',
    dialCode: '+370',
    phoneExample: '612 34567',
  },
  {
    country: 'Luxembourg',
    code: 'LU',
    currency: 'eur',
    timezone: 'Europe/Luxembourg',
    emoji: '🇱🇺',
    dialCode: '+352',
    phoneExample: '628 123 456',
  },
  {
    country: 'Macao SAR China',
    code: 'MO',
    currency: 'mop',
    timezone: 'Asia/Macau',
    emoji: '🇲🇴',
    dialCode: '+853',
    phoneExample: '6612 3456',
  },
  {
    country: 'Madagascar',
    code: 'MG',
    currency: 'mga',
    timezone: 'Indian/Antananarivo',
    emoji: '🇲🇬',
    dialCode: '+261',
    phoneExample: '32 11 123 45',
  },
  {
    country: 'Malawi',
    code: 'MW',
    currency: 'mwk',
    timezone: 'Africa/Blantyre',
    emoji: '🇲🇼',
    dialCode: '+265',
    phoneExample: '991 23 45 67',
  },
  {
    country: 'Malaysia',
    code: 'MY',
    currency: 'myr',
    timezone: 'Asia/Kuala_Lumpur',
    emoji: '🇲🇾',
    dialCode: '+60',
    phoneExample: '12 345 6789',
  },
  {
    country: 'Maldives',
    code: 'MV',
    currency: 'mvr',
    timezone: 'Indian/Maldives',
    emoji: '🇲🇻',
    dialCode: '+960',
    phoneExample: '771 2345',
  },
  {
    country: 'Mali',
    code: 'ML',
    currency: 'xof',
    timezone: 'Africa/Bamako',
    emoji: '🇲🇱',
    dialCode: '+223',
    phoneExample: '65 01 23 45',
  },
  {
    country: 'Malta',
    code: 'MT',
    currency: 'eur',
    timezone: 'Europe/Malta',
    emoji: '🇲🇹',
    dialCode: '+356',
    phoneExample: '9696 1234',
  },
  {
    country: 'Marshall Islands',
    code: 'MH',
    currency: 'usd',
    timezone: 'Pacific/Majuro',
    emoji: '🇲🇭',
    dialCode: '+692',
    phoneExample: '235 1234',
  },
  {
    country: 'Martinique',
    code: 'MQ',
    currency: 'eur',
    timezone: 'America/Martinique',
    emoji: '🇲🇶',
    dialCode: '+596',
    phoneExample: '696 20 12 34',
  },
  {
    country: 'Mauritania',
    code: 'MR',
    currency: 'mru',
    timezone: 'Africa/Nouakchott',
    emoji: '🇲🇷',
    dialCode: '+222',
    phoneExample: '22 12 34 56',
  },
  {
    country: 'Mauritius',
    code: 'MU',
    currency: 'mur',
    timezone: 'Indian/Mauritius',
    emoji: '🇲🇺',
    dialCode: '+230',
    phoneExample: '5251 2345',
  },
  {
    country: 'Mayotte',
    code: 'YT',
    currency: 'eur',
    timezone: 'Indian/Mayotte',
    emoji: '🇾🇹',
    dialCode: '+262',
    phoneExample: '639 01 23 45',
  },
  {
    country: 'Mexico',
    code: 'MX',
    currency: 'mxn',
    timezone: 'America/Mexico_City',
    emoji: '🇲🇽',
    dialCode: '+52',
    phoneExample: '55 1234 5678',
  },
  {
    country: 'Micronesia',
    code: 'FM',
    currency: 'usd',
    timezone: 'Pacific/Pohnpei',
    emoji: '🇫🇲',
    dialCode: '+691',
    phoneExample: '350 1234',
  },
  {
    country: 'Moldova',
    code: 'MD',
    currency: 'mdl',
    timezone: 'Europe/Chisinau',
    emoji: '🇲🇩',
    dialCode: '+373',
    phoneExample: '621 12 345',
  },
  {
    country: 'Monaco',
    code: 'MC',
    currency: 'eur',
    timezone: 'Europe/Monaco',
    emoji: '🇲🇨',
    dialCode: '+377',
    phoneExample: '6 12 34 56 78',
  },
  {
    country: 'Mongolia',
    code: 'MN',
    currency: 'mnt',
    timezone: 'Asia/Ulaanbaatar',
    emoji: '🇲🇳',
    dialCode: '+976',
    phoneExample: '8812 3456',
  },
  {
    country: 'Montenegro',
    code: 'ME',
    currency: 'eur',
    timezone: 'Europe/Podgorica',
    emoji: '🇲🇪',
    dialCode: '+382',
    phoneExample: '67 622 901',
  },
  {
    country: 'Montserrat',
    code: 'MS',
    currency: 'xcd',
    timezone: 'America/Montserrat',
    emoji: '🇲🇸',
    dialCode: '+1664',
    phoneExample: '492 3456',
  },
  {
    country: 'Morocco',
    code: 'MA',
    currency: 'mad',
    timezone: 'Africa/Casablanca',
    emoji: '🇲🇦',
    dialCode: '+212',
    phoneExample: '650 123456',
  },
  {
    country: 'Mozambique',
    code: 'MZ',
    currency: 'mzn',
    timezone: 'Africa/Maputo',
    emoji: '🇲🇿',
    dialCode: '+258',
    phoneExample: '82 123 4567',
  },
  {
    country: 'Myanmar',
    code: 'MM',
    currency: 'mmk',
    timezone: 'Asia/Yangon',
    emoji: '🇲🇲',
    dialCode: '+95',
    phoneExample: '9 212 3456',
  },
  {
    country: 'Namibia',
    code: 'NA',
    currency: 'nad',
    timezone: 'Africa/Windhoek',
    emoji: '🇳🇦',
    dialCode: '+264',
    phoneExample: '81 123 4567',
  },
  {
    country: 'Nauru',
    code: 'NR',
    currency: 'aud',
    timezone: 'Pacific/Nauru',
    emoji: '🇳🇷',
    dialCode: '+674',
    phoneExample: '555 1234',
  },
  {
    country: 'Nepal',
    code: 'NP',
    currency: 'npr',
    timezone: 'Asia/Kathmandu',
    emoji: '🇳🇵',
    dialCode: '+977',
    phoneExample: '984 1234567',
  },
  {
    country: 'Netherlands',
    code: 'NL',
    currency: 'eur',
    timezone: 'Europe/Amsterdam',
    emoji: '🇳🇱',
    dialCode: '+31',
    phoneExample: '6 12345678',
  },
  {
    country: 'New Caledonia',
    code: 'NC',
    currency: 'xpf',
    timezone: 'Pacific/Noumea',
    emoji: '🇳🇨',
    dialCode: '+687',
    phoneExample: '75 12 34',
  },
  {
    country: 'New Zealand',
    code: 'NZ',
    currency: 'nzd',
    timezone: 'Pacific/Auckland',
    emoji: '🇳🇿',
    dialCode: '+64',
    phoneExample: '21 123 4567',
  },
  {
    country: 'Nicaragua',
    code: 'NI',
    currency: 'nio',
    timezone: 'America/Managua',
    emoji: '🇳🇮',
    dialCode: '+505',
    phoneExample: '8123 4567',
  },
  {
    country: 'Niger',
    code: 'NE',
    currency: 'xof',
    timezone: 'Africa/Niamey',
    emoji: '🇳🇪',
    dialCode: '+227',
    phoneExample: '93 12 34 56',
  },
  {
    country: 'Nigeria',
    code: 'NG',
    currency: 'ngn',
    timezone: 'Africa/Lagos',
    emoji: '🇳🇬',
    dialCode: '+234',
    phoneExample: '802 123 4567',
  },
  {
    country: 'Niue',
    code: 'NU',
    currency: 'nzd',
    timezone: 'Pacific/Niue',
    emoji: '🇳🇺',
    dialCode: '+683',
    phoneExample: '888 4012',
  },
  {
    country: 'North Macedonia',
    code: 'MK',
    currency: 'mkd',
    timezone: 'Europe/Skopje',
    emoji: '🇲🇰',
    dialCode: '+389',
    phoneExample: '72 345 678',
  },
  {
    country: 'Northern Mariana Islands',
    code: 'MP',
    currency: 'usd',
    timezone: 'Pacific/Guam',
    emoji: '🇲🇵',
    dialCode: '+1670',
    phoneExample: '234 5678',
  },
  {
    country: 'Norway',
    code: 'NO',
    currency: 'nok',
    timezone: 'Europe/Oslo',
    emoji: '🇳🇴',
    dialCode: '+47',
    phoneExample: '412 34 567',
  },
  {
    country: 'Oman',
    code: 'OM',
    currency: 'omr',
    timezone: 'Asia/Muscat',
    emoji: '🇴🇲',
    dialCode: '+968',
    phoneExample: '9212 3456',
  },
  {
    country: 'Pakistan',
    code: 'PK',
    currency: 'pkr',
    timezone: 'Asia/Karachi',
    emoji: '🇵🇰',
    dialCode: '+92',
    phoneExample: '301 2345678',
  },
  {
    country: 'Palau',
    code: 'PW',
    currency: 'usd',
    timezone: 'Pacific/Palau',
    emoji: '🇵🇼',
    dialCode: '+680',
    phoneExample: '620 1234',
  },
  {
    country: 'Palestine',
    code: 'PS',
    currency: 'ils',
    timezone: 'Asia/Hebron',
    emoji: '🇵🇸',
    dialCode: '+970',
    phoneExample: '59 912 3456',
  },
  {
    country: 'Panama',
    code: 'PA',
    currency: 'pab',
    timezone: 'America/Panama',
    emoji: '🇵🇦',
    dialCode: '+507',
    phoneExample: '6123 4567',
  },
  {
    country: 'Papua New Guinea',
    code: 'PG',
    currency: 'pgk',
    timezone: 'Pacific/Port_Moresby',
    emoji: '🇵🇬',
    dialCode: '+675',
    phoneExample: '7012 3456',
  },
  {
    country: 'Paraguay',
    code: 'PY',
    currency: 'pyg',
    timezone: 'America/Asuncion',
    emoji: '🇵🇾',
    dialCode: '+595',
    phoneExample: '961 456789',
  },
  {
    country: 'Peru',
    code: 'PE',
    currency: 'pen',
    timezone: 'America/Lima',
    emoji: '🇵🇪',
    dialCode: '+51',
    phoneExample: '912 345 678',
  },
  {
    country: 'Philippines',
    code: 'PH',
    currency: 'php',
    timezone: 'Asia/Manila',
    emoji: '🇵🇭',
    dialCode: '+63',
    phoneExample: '917 123 4567',
  },
  {
    country: 'Poland',
    code: 'PL',
    currency: 'pln',
    timezone: 'Europe/Warsaw',
    emoji: '🇵🇱',
    dialCode: '+48',
    phoneExample: '512 345 678',
  },
  {
    country: 'Portugal',
    code: 'PT',
    currency: 'eur',
    timezone: 'Europe/Lisbon',
    emoji: '🇵🇹',
    dialCode: '+351',
    phoneExample: '912 345 678',
  },
  {
    country: 'Puerto Rico',
    code: 'PR',
    currency: 'usd',
    timezone: 'America/Puerto_Rico',
    emoji: '🇵🇷',
    dialCode: '+1787',
    phoneExample: '234 5678',
  },
  {
    country: 'Qatar',
    code: 'QA',
    currency: 'qar',
    timezone: 'Asia/Qatar',
    emoji: '🇶🇦',
    dialCode: '+974',
    phoneExample: '3312 3456',
  },
  {
    country: 'Réunion',
    code: 'RE',
    currency: 'eur',
    timezone: 'Indian/Reunion',
    emoji: '🇷🇪',
    dialCode: '+262',
    phoneExample: '692 12 34 56',
  },
  {
    country: 'Romania',
    code: 'RO',
    currency: 'ron',
    timezone: 'Europe/Bucharest',
    emoji: '🇷🇴',
    dialCode: '+40',
    phoneExample: '712 345 678',
  },
  {
    country: 'Russia',
    code: 'RU',
    currency: 'rub',
    timezone: 'Europe/Moscow',
    emoji: '🇷🇺',
    dialCode: '+7',
    phoneExample: '912 345 67 89',
  },
  {
    country: 'Rwanda',
    code: 'RW',
    currency: 'rwf',
    timezone: 'Africa/Kigali',
    emoji: '🇷🇼',
    dialCode: '+250',
    phoneExample: '78 123 4567',
  },
  {
    country: 'Samoa',
    code: 'WS',
    currency: 'wst',
    timezone: 'Pacific/Apia',
    emoji: '🇼🇸',
    dialCode: '+685',
    phoneExample: '72 12345',
  },
  {
    country: 'San Marino',
    code: 'SM',
    currency: 'eur',
    timezone: 'Europe/San_Marino',
    emoji: '🇸🇲',
    dialCode: '+378',
    phoneExample: '66 12 12 12',
  },
  {
    country: 'São Tomé & Príncipe',
    code: 'ST',
    currency: 'stn',
    timezone: 'Africa/Sao_Tome',
    emoji: '🇸🇹',
    dialCode: '+239',
    phoneExample: '981 2345',
  },
  {
    country: 'Saudi Arabia',
    code: 'SA',
    currency: 'sar',
    timezone: 'Asia/Riyadh',
    emoji: '🇸🇦',
    dialCode: '+966',
    phoneExample: '51 234 5678',
  },
  {
    country: 'Senegal',
    code: 'SN',
    currency: 'xof',
    timezone: 'Africa/Dakar',
    emoji: '🇸🇳',
    dialCode: '+221',
    phoneExample: '70 123 45 67',
  },
  {
    country: 'Serbia',
    code: 'RS',
    currency: 'rsd',
    timezone: 'Europe/Belgrade',
    emoji: '🇷🇸',
    dialCode: '+381',
    phoneExample: '60 1234567',
  },
  {
    country: 'Seychelles',
    code: 'SC',
    currency: 'scr',
    timezone: 'Indian/Mahe',
    emoji: '🇸🇨',
    dialCode: '+248',
    phoneExample: '2 510 123',
  },
  {
    country: 'Sierra Leone',
    code: 'SL',
    currency: 'sll',
    timezone: 'Africa/Freetown',
    emoji: '🇸🇱',
    dialCode: '+232',
    phoneExample: '25 123456',
  },
  {
    country: 'Singapore',
    code: 'SG',
    currency: 'sgd',
    timezone: 'Asia/Singapore',
    emoji: '🇸🇬',
    dialCode: '+65',
    phoneExample: '8123 4567',
  },
  {
    country: 'Sint Maarten',
    code: 'SX',
    currency: 'ang',
    timezone: 'America/Lower_Princes',
    emoji: '🇸🇽',
    dialCode: '+1721',
    phoneExample: '520 1234',
  },
  {
    country: 'Slovakia',
    code: 'SK',
    currency: 'eur',
    timezone: 'Europe/Bratislava',
    emoji: '🇸🇰',
    dialCode: '+421',
    phoneExample: '912 123 456',
  },
  {
    country: 'Slovenia',
    code: 'SI',
    currency: 'eur',
    timezone: 'Europe/Ljubljana',
    emoji: '🇸🇮',
    dialCode: '+386',
    phoneExample: '31 234 567',
  },
  {
    country: 'Solomon Islands',
    code: 'SB',
    currency: 'sbd',
    timezone: 'Pacific/Guadalcanal',
    emoji: '🇸🇧',
    dialCode: '+677',
    phoneExample: '74 21234',
  },
  {
    country: 'Somalia',
    code: 'SO',
    currency: 'sos',
    timezone: 'Africa/Mogadishu',
    emoji: '🇸🇴',
    dialCode: '+252',
    phoneExample: '90 1234567',
  },
  {
    country: 'South Africa',
    code: 'ZA',
    currency: 'zar',
    timezone: 'Africa/Johannesburg',
    emoji: '🇿🇦',
    dialCode: '+27',
    phoneExample: '71 123 4567',
  },
  {
    country: 'South Korea',
    code: 'KR',
    currency: 'krw',
    timezone: 'Asia/Seoul',
    emoji: '🇰🇷',
    dialCode: '+82',
    phoneExample: '10 1234 5678',
  },
  {
    country: 'South Sudan',
    code: 'SS',
    currency: 'ssp',
    timezone: 'Africa/Juba',
    emoji: '🇸🇸',
    dialCode: '+211',
    phoneExample: '977 123 456',
  },
  {
    country: 'Spain',
    code: 'ES',
    currency: 'eur',
    timezone: 'Europe/Madrid',
    emoji: '🇪🇸',
    dialCode: '+34',
    phoneExample: '612 34 56 78',
  },
  {
    country: 'Sri Lanka',
    code: 'LK',
    currency: 'lkr',
    timezone: 'Asia/Colombo',
    emoji: '🇱🇰',
    dialCode: '+94',
    phoneExample: '71 234 5678',
  },
  {
    country: 'St. Barthélemy',
    code: 'BL',
    currency: 'eur',
    timezone: 'America/St_Barthelemy',
    emoji: '🇧🇱',
    dialCode: '+590',
    phoneExample: '690 00 12 34',
  },
  {
    country: 'St. Kitts & Nevis',
    code: 'KN',
    currency: 'xcd',
    timezone: 'America/St_Kitts',
    emoji: '🇰🇳',
    dialCode: '+1869',
    phoneExample: '765 1234',
  },
  {
    country: 'St. Lucia',
    code: 'LC',
    currency: 'xcd',
    timezone: 'America/St_Lucia',
    emoji: '🇱🇨',
    dialCode: '+1758',
    phoneExample: '284 5678',
  },
  {
    country: 'St. Martin',
    code: 'MF',
    currency: 'eur',
    timezone: 'America/Marigot',
    emoji: '🇲🇫',
    dialCode: '+590',
    phoneExample: '690 00 12 34',
  },
  {
    country: 'St. Vincent & the Grenadines',
    code: 'VC',
    currency: 'xcd',
    timezone: 'America/St_Vincent',
    emoji: '🇻🇨',
    dialCode: '+1784',
    phoneExample: '430 1234',
  },
  {
    country: 'Sudan',
    code: 'SD',
    currency: 'sdg',
    timezone: 'Africa/Khartoum',
    emoji: '🇸🇩',
    dialCode: '+249',
    phoneExample: '91 123 1234',
  },
  {
    country: 'Suriname',
    code: 'SR',
    currency: 'srd',
    timezone: 'America/Paramaribo',
    emoji: '🇸🇷',
    dialCode: '+597',
    phoneExample: '741 2345',
  },
  {
    country: 'Sweden',
    code: 'SE',
    currency: 'sek',
    timezone: 'Europe/Stockholm',
    emoji: '🇸🇪',
    dialCode: '+46',
    phoneExample: '70 123 45 67',
  },
  {
    country: 'Switzerland',
    code: 'CH',
    currency: 'chf',
    timezone: 'Europe/Zurich',
    emoji: '🇨🇭',
    dialCode: '+41',
    phoneExample: '78 123 45 67',
  },
  {
    country: 'Taiwan',
    code: 'TW',
    currency: 'twd',
    timezone: 'Asia/Taipei',
    emoji: '🇹🇼',
    dialCode: '+886',
    phoneExample: '912 345 678',
  },
  {
    country: 'Tajikistan',
    code: 'TJ',
    currency: 'tjs',
    timezone: 'Asia/Dushanbe',
    emoji: '🇹🇯',
    dialCode: '+992',
    phoneExample: '917 12 3456',
  },
  {
    country: 'Tanzania',
    code: 'TZ',
    currency: 'tzs',
    timezone: 'Africa/Dar_es_Salaam',
    emoji: '🇹🇿',
    dialCode: '+255',
    phoneExample: '621 234 567',
  },
  {
    country: 'Thailand',
    code: 'TH',
    currency: 'thb',
    timezone: 'Asia/Bangkok',
    emoji: '🇹🇭',
    dialCode: '+66',
    phoneExample: '81 234 5678',
  },
  {
    country: 'Timor-Leste',
    code: 'TL',
    currency: 'usd',
    timezone: 'Asia/Dili',
    emoji: '🇹🇱',
    dialCode: '+670',
    phoneExample: '7712 3456',
  },
  {
    country: 'Togo',
    code: 'TG',
    currency: 'xof',
    timezone: 'Africa/Lome',
    emoji: '🇹🇬',
    dialCode: '+228',
    phoneExample: '90 12 34 56',
  },
  {
    country: 'Tonga',
    code: 'TO',
    currency: 'top',
    timezone: 'Pacific/Tongatapu',
    emoji: '🇹🇴',
    dialCode: '+676',
    phoneExample: '771 5123',
  },
  {
    country: 'Trinidad & Tobago',
    code: 'TT',
    currency: 'ttd',
    timezone: 'America/Port_of_Spain',
    emoji: '🇹🇹',
    dialCode: '+1868',
    phoneExample: '291 1234',
  },
  {
    country: 'Tunisia',
    code: 'TN',
    currency: 'tnd',
    timezone: 'Africa/Tunis',
    emoji: '🇹🇳',
    dialCode: '+216',
    phoneExample: '20 123 456',
  },
  {
    country: 'Turkey',
    code: 'TR',
    currency: 'try',
    timezone: 'Europe/Istanbul',
    emoji: '🇹🇷',
    dialCode: '+90',
    phoneExample: '501 234 56 78',
  },
  {
    country: 'Turkmenistan',
    code: 'TM',
    currency: 'tmt',
    timezone: 'Asia/Ashgabat',
    emoji: '🇹🇲',
    dialCode: '+993',
    phoneExample: '66 123456',
  },
  {
    country: 'Turks & Caicos Islands',
    code: 'TC',
    currency: 'usd',
    timezone: 'America/Grand_Turk',
    emoji: '🇹🇨',
    dialCode: '+1649',
    phoneExample: '231 1234',
  },
  {
    country: 'Tuvalu',
    code: 'TV',
    currency: 'aud',
    timezone: 'Pacific/Funafuti',
    emoji: '🇹🇻',
    dialCode: '+688',
    phoneExample: '90 1234',
  },
  {
    country: 'Uganda',
    code: 'UG',
    currency: 'ugx',
    timezone: 'Africa/Kampala',
    emoji: '🇺🇬',
    dialCode: '+256',
    phoneExample: '712 345678',
  },
  {
    country: 'Ukraine',
    code: 'UA',
    currency: 'uah',
    timezone: 'Europe/Kiev',
    emoji: '🇺🇦',
    dialCode: '+380',
    phoneExample: '50 123 4567',
  },
  {
    country: 'United Arab Emirates',
    code: 'AE',
    currency: 'aed',
    timezone: 'Asia/Dubai',
    emoji: '🇦🇪',
    dialCode: '+971',
    phoneExample: '50 123 4567',
  },
  {
    country: 'United Kingdom',
    code: 'GB',
    currency: 'gbp',
    timezone: 'Europe/London',
    emoji: '🇬🇧',
    dialCode: '+44',
    phoneExample: '7911 123456',
  },
  {
    country: 'United States',
    code: 'US',
    currency: 'usd',
    timezone: 'America/New_York',
    emoji: '🇺🇸',
    dialCode: '+1',
    phoneExample: '555 123 4567',
  },
  {
    country: 'Uruguay',
    code: 'UY',
    currency: 'uyu',
    timezone: 'America/Montevideo',
    emoji: '🇺🇾',
    dialCode: '+598',
    phoneExample: '94 231 234',
  },
  {
    country: 'US Virgin Islands',
    code: 'VI',
    currency: 'usd',
    timezone: 'America/Virgin',
    emoji: '🇻🇮',
    dialCode: '+1340',
    phoneExample: '642 1234',
  },
  {
    country: 'Uzbekistan',
    code: 'UZ',
    currency: 'uzs',
    timezone: 'Asia/Tashkent',
    emoji: '🇺🇿',
    dialCode: '+998',
    phoneExample: '91 234 56 78',
  },
  {
    country: 'Vanuatu',
    code: 'VU',
    currency: 'vuv',
    timezone: 'Pacific/Efate',
    emoji: '🇻🇺',
    dialCode: '+678',
    phoneExample: '591 2345',
  },
  {
    country: 'Venezuela',
    code: 'VE',
    currency: 'ves',
    timezone: 'America/Caracas',
    emoji: '🇻🇪',
    dialCode: '+58',
    phoneExample: '412 123 4567',
  },
  {
    country: 'Vietnam',
    code: 'VN',
    currency: 'vnd',
    timezone: 'Asia/Ho_Chi_Minh',
    emoji: '🇻🇳',
    dialCode: '+84',
    phoneExample: '91 234 56 78',
  },
  {
    country: 'Yemen',
    code: 'YE',
    currency: 'yer',
    timezone: 'Asia/Aden',
    emoji: '🇾🇪',
    dialCode: '+967',
    phoneExample: '712 345 678',
  },
  {
    country: 'Zambia',
    code: 'ZM',
    currency: 'zmw',
    timezone: 'Africa/Lusaka',
    emoji: '🇿🇲',
    dialCode: '+260',
    phoneExample: '95 5123456',
  },
  {
    country: 'Zimbabwe',
    code: 'ZW',
    currency: 'zwl',
    timezone: 'Africa/Harare',
    emoji: '🇿🇼',
    dialCode: '+263',
    phoneExample: '71 234 5678',
  },
];

export function GetCountryByCode(code: string): CountryCode | undefined {
  return ISO_CODES.find((c) => c.code === code);
}

export function GetCountryName(code: string): string {
  return GetCountryByCode(code)?.country || '';
}

export function GetCountryDialCode(code: string): string {
  return GetCountryByCode(code)?.dialCode || '+1';
}
