import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {
  MergeEnvironment,
  ResolveEnvironmentTarget,
  SyncEnvironment,
} from './EnvSync';
import { ProfileStore } from './ProfileStore';
import {
  GetApiKeyAccount,
  GetWalletAccount,
  type SecretStore,
} from './SecretStore';

describe('Environment sync', () => {
  let configRoot: string;
  let projectDirectory: string;
  let secretStore: SecretStore;
  let secrets: Map<string, string>;

  beforeEach(async () => {
    configRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'zoneless-config-'));
    projectDirectory = await fs.realpath(
      await fs.mkdtemp(path.join(os.tmpdir(), 'zoneless-env-'))
    );
    secrets = new Map();
    secretStore = {
      Delete: async (account) => {
        secrets.delete(account);
      },
      Get: async (account) => secrets.get(account) ?? null,
      Set: async (account, value) => {
        secrets.set(account, value);
      },
    };
  });

  afterEach(async () => {
    await Promise.all([
      fs.rm(configRoot, { force: true, recursive: true }),
      fs.rm(projectDirectory, { force: true, recursive: true }),
    ]);
  });

  it('updates existing values without overwriting unrelated configuration', () => {
    expect(
      MergeEnvironment('PORT=3000\nZONELESS_API_KEY=old\n', {
        ZONELESS_API_KEY: 'new',
        ZONELESS_API_URL: 'https://api-test.zoneless.com',
      })
    ).toBe(
      [
        'PORT=3000',
        'ZONELESS_API_KEY=new',
        '',
        '# Generated by zoneless env sync for local development.',
        'ZONELESS_API_URL=https://api-test.zoneless.com',
        '',
      ].join('\n')
    );
  });

  it('selects the only existing env file and requires a choice when ambiguous', async () => {
    await fs.writeFile(
      path.join(projectDirectory, '.env.local'),
      'PORT=3000\n'
    );
    await expect(ResolveEnvironmentTarget(projectDirectory)).resolves.toBe(
      path.join(projectDirectory, '.env.local')
    );

    await fs.writeFile(path.join(projectDirectory, '.env'), 'OTHER=value\n');
    await expect(ResolveEnvironmentTarget(projectDirectory)).rejects.toThrow(
      /Multiple environment files/
    );
  });

  it('syncs API and wallet credentials without returning their values', async () => {
    const profileStore = new ProfileStore(
      { XDG_CONFIG_HOME: configRoot },
      secretStore
    );
    const walletPublicKey = 'wallet-public-key';
    await profileStore.SaveProfiles(
      {
        test: {
          apiKeyPrefix: 'zk_test',
          apiUrl: 'https://api-test.zoneless.com/v1',
          mode: 'test',
          platformId: 'platform-test',
          platformName: 'Acme',
          walletPublicKey,
          workspaceId: 'workspace-acme',
        },
      },
      { test: 'zk_test_secret' }
    );
    await secretStore.Set(
      GetWalletAccount(walletPublicKey),
      Buffer.alloc(64, 7).toString('base64')
    );

    const result = await SyncEnvironment(
      {
        includeWallet: true,
        profileName: 'test',
        projectDirectory,
      },
      profileStore,
      secretStore
    );

    const contents = await fs.readFile(
      path.join(projectDirectory, '.env'),
      'utf8'
    );
    expect(contents).toContain('ZONELESS_API_KEY=zk_test_secret');
    expect(contents).toContain(
      'ZONELESS_API_URL=https://api-test.zoneless.com'
    );
    expect(contents).toContain('SOLANA_SECRET_KEY=');
    expect(JSON.stringify(result)).not.toContain('zk_test_secret');
    expect(result.written).toEqual([
      'ZONELESS_API_KEY',
      'ZONELESS_API_URL',
      'SOLANA_SECRET_KEY',
    ]);
    expect((await fs.stat(result.target)).mode & 0o777).toBe(0o600);
    expect(
      await fs.readFile(path.join(projectDirectory, '.gitignore'), 'utf8')
    ).toBe('.env\n');
    expect(await secretStore.Get(GetApiKeyAccount('test'))).toBe(
      'zk_test_secret'
    );
  });
});
