import fs from 'node:fs/promises';
import path from 'node:path';
import { InvalidInput } from './Errors';
import type { ProfileStore } from './ProfileStore';
import { GetWalletAccount, type SecretStore } from './SecretStore';
import { CreateWalletBackup } from './Wallet';

const environmentCandidates = ['.env', '.env.local', '.env.development.local'];

export interface EnvSyncOptions {
  includeWallet: boolean;
  profileName: string;
  projectDirectory: string;
  target?: string;
}

export interface EnvSyncResult {
  file_mode: '0600';
  mode: 'live' | 'test';
  object: 'env_sync';
  ok: true;
  profile: string;
  target: string;
  written: string[];
}

export async function SyncEnvironment(
  options: EnvSyncOptions,
  profileStore: ProfileStore,
  secretStore: SecretStore
): Promise<EnvSyncResult> {
  const credentials = await profileStore.GetCredentials(options.profileName);
  const targetPath = await ResolveEnvironmentTarget(
    options.projectDirectory,
    options.target
  );
  const values: Record<string, string> = {
    ZONELESS_API_KEY: credentials.apiKey,
    ZONELESS_API_URL: credentials.profile.apiUrl.replace(/\/v1\/?$/, ''),
  };

  if (options.includeWallet) {
    const secretKeyBase64 = await secretStore.Get(
      GetWalletAccount(credentials.profile.walletPublicKey)
    );
    if (!secretKeyBase64) {
      throw InvalidInput(
        `The wallet key for profile "${options.profileName}" is missing from the credential store.`
      );
    }
    values['SOLANA_SECRET_KEY'] = CreateWalletBackup(
      credentials.profile.walletPublicKey,
      secretKeyBase64
    ).secretKeyBase58;
  }

  let contents = '';
  try {
    contents = await fs.readFile(targetPath, 'utf8');
  } catch (error) {
    const nodeError = error as NodeJS.ErrnoException;
    if (nodeError.code !== 'ENOENT') throw error;
  }

  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  const temporaryPath = `${targetPath}.${process.pid}.tmp`;
  await fs.writeFile(temporaryPath, MergeEnvironment(contents, values), {
    mode: 0o600,
  });
  await fs.rename(temporaryPath, targetPath);
  await fs.chmod(targetPath, 0o600);
  await EnsureGitignored(options.projectDirectory, targetPath);

  return {
    file_mode: '0600',
    mode: credentials.profile.mode,
    object: 'env_sync',
    ok: true,
    profile: options.profileName,
    target: targetPath,
    written: Object.keys(values),
  };
}

export async function ResolveEnvironmentTarget(
  projectDirectory: string,
  explicitTarget?: string
): Promise<string> {
  const resolvedProject = path.resolve(projectDirectory);
  if (explicitTarget) {
    const targetPath = path.resolve(resolvedProject, explicitTarget);
    EnsureInsideProject(resolvedProject, targetPath);
    return targetPath;
  }

  const existingCandidates: Array<{ path: string; zoneless: boolean }> = [];
  for (const candidate of environmentCandidates) {
    const candidatePath = path.join(resolvedProject, candidate);
    try {
      const contents = await fs.readFile(candidatePath, 'utf8');
      existingCandidates.push({
        path: candidatePath,
        zoneless:
          contents.includes('ZONELESS_API_KEY') ||
          contents.includes('ZONELESS_API_URL'),
      });
    } catch (error) {
      const nodeError = error as NodeJS.ErrnoException;
      if (nodeError.code !== 'ENOENT') throw error;
    }
  }

  const zonelessCandidates = existingCandidates.filter(
    (candidate) => candidate.zoneless
  );
  if (zonelessCandidates.length === 1) return zonelessCandidates[0].path;
  if (zonelessCandidates.length > 1 || existingCandidates.length > 1) {
    const candidates = (
      zonelessCandidates.length > 1 ? zonelessCandidates : existingCandidates
    )
      .map((candidate) => path.basename(candidate.path))
      .join(', ');
    throw InvalidInput(
      `Multiple environment files were found (${candidates}). Choose one with --target.`
    );
  }
  if (existingCandidates.length === 1) return existingCandidates[0].path;

  return path.join(
    resolvedProject,
    (await UsesLocalEnvironmentConvention(resolvedProject))
      ? '.env.local'
      : '.env'
  );
}

export function MergeEnvironment(
  contents: string,
  values: Record<string, string>
): string {
  const remaining = new Map(Object.entries(values));
  const lines = contents ? contents.replace(/\n$/, '').split('\n') : [];
  const merged = lines.map((line) => {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=/);
    if (!match || !remaining.has(match[1])) return line;
    const value = remaining.get(match[1])!;
    remaining.delete(match[1]);
    return `${match[1]}=${value}`;
  });

  if (remaining.size > 0) {
    if (merged.length > 0 && merged[merged.length - 1] !== '') merged.push('');
    merged.push('# Generated by zoneless env sync for local development.');
    for (const [key, value] of remaining) merged.push(`${key}=${value}`);
  }

  return `${merged.join('\n')}\n`;
}

async function UsesLocalEnvironmentConvention(
  projectDirectory: string
): Promise<boolean> {
  try {
    const packageJson = JSON.parse(
      await fs.readFile(path.join(projectDirectory, 'package.json'), 'utf8')
    ) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const dependencies = {
      ...packageJson.dependencies,
      ...packageJson.devDependencies,
    };
    return Boolean(dependencies['next'] || dependencies['vite']);
  } catch (error) {
    const nodeError = error as NodeJS.ErrnoException;
    if (nodeError.code === 'ENOENT') return false;
    throw error;
  }
}

async function EnsureGitignored(
  projectDirectory: string,
  targetPath: string
): Promise<void> {
  const relativeTarget = path.relative(projectDirectory, targetPath);
  EnsureInsideProject(projectDirectory, targetPath);
  const gitignorePath = path.join(projectDirectory, '.gitignore');
  let contents = '';
  try {
    contents = await fs.readFile(gitignorePath, 'utf8');
  } catch (error) {
    const nodeError = error as NodeJS.ErrnoException;
    if (nodeError.code !== 'ENOENT') throw error;
  }

  const normalizedTarget = relativeTarget.split(path.sep).join('/');
  const existingRules = new Set(
    contents
      .split('\n')
      .map((line) => line.trim())
      .filter(Boolean)
  );
  if (
    existingRules.has(normalizedTarget) ||
    existingRules.has(`/${normalizedTarget}`) ||
    (normalizedTarget === '.env' && existingRules.has('.env*')) ||
    (normalizedTarget.startsWith('.env.') && existingRules.has('.env*'))
  ) {
    return;
  }

  const prefix = contents && !contents.endsWith('\n') ? '\n' : '';
  await fs.writeFile(
    gitignorePath,
    `${contents}${prefix}${normalizedTarget}\n`
  );
}

function EnsureInsideProject(
  projectDirectory: string,
  targetPath: string
): void {
  const relative = path.relative(projectDirectory, targetPath);
  if (relative.startsWith('..') || path.isAbsolute(relative)) {
    throw InvalidInput('The environment target must be inside the project.');
  }
}
